In [1]:
import pandas as pd
import numpy as np 
import sqlite3

conn = sqlite3.connect("8803.db")

In [5]:
# edges = pd.read_csv('csv_paradise_papers.2018-02-14/paradise_papers.edges.csv', low_memory = False)
# address = pd.read_csv('csv_paradise_papers.2018-02-14/paradise_papers.nodes.address.csv', low_memory = False)

edges = pd.read_sql("""select * from edges""", conn)
address = pd.read_sql("""select * from address""", conn)

In [3]:
# edges.to_sql("edges",conn, if_exists = "replace")
# address.to_sql("address", conn, if_exists = "replace")

In [4]:
address.columns

Index(['node_id', 'name', 'address', 'country_codes', 'countries', 'sourceID',
       'valid_until', 'note'],
      dtype='object')

In [6]:
df = pd.read_sql("""select a.START_ID, b.countries from edges as a inner join 
(select START_ID, countries from edges inner join address on END_ID = node_id ) as b
on a.END_ID=b.START_ID
                """, conn)

In [7]:
df

         START_ID countries
0        85004929     Aruba
1        85004929     Aruba
2        85008443     Aruba
3        85008450     Aruba
4        85008462     Aruba
5        85008483     Aruba
6        85008517     Aruba
7        85008542     Aruba
8        85008549     Aruba
9        85008559     Aruba
10       85008561     Aruba
11       85008561     Aruba
12       85008561     Aruba
13       85008561     Aruba
14       85008561     Aruba
15       85008561     Aruba
16       85008561     Aruba
17       85008561     Aruba
18       85008561     Aruba
19       85008561     Aruba
20       85008561     Aruba
21       85008561     Aruba
22       85008561     Aruba
23       85008561     Aruba
24       85008561     Aruba
25       85008561     Aruba
26       85008561     Aruba
27       85008561     Aruba
28       85008561     Aruba
29       85008561     Aruba
...           ...       ...
1352381  66003233     Samoa
1352382  66003233     Samoa
1352383  66005305     Samoa
1352384  66005305     Samoa
1352385  66005305     Samoa
1352386  66001047     Samoa
1352387  66004302     Samoa
1352388  66005378     Samoa
1352389  66005170     Samoa
1352390  66002180     Samoa
1352391  66002180     Samoa
1352392  66005107     Samoa
1352393  66004354     Samoa
1352394  66002941     Samoa
1352395  66005116     Samoa
1352396  66005019  Pakistan
1352397  66005268     Samoa
1352398  66002528     Samoa
1352399  66001893     Samoa
1352400  66003658     Samoa
1352401  66004065     Samoa
1352402  66000388     Samoa
1352403  66003276     Samoa
1352404  66004625     Samoa
1352405  66005381     India
1352406  66005381     Samoa
1352407  66005369     Samoa
1352408  66005369     Samoa
1352409  66001573     Samoa
1352410  66001573     Samoa

[1352411 rows x 2 columns]

In [8]:
df = df.rename(columns = {"START_ID":"node_id"})
df

          node_id countries
0        85004929     Aruba
1        85004929     Aruba
2        85008443     Aruba
3        85008450     Aruba
4        85008462     Aruba
5        85008483     Aruba
6        85008517     Aruba
7        85008542     Aruba
8        85008549     Aruba
9        85008559     Aruba
10       85008561     Aruba
11       85008561     Aruba
12       85008561     Aruba
13       85008561     Aruba
14       85008561     Aruba
15       85008561     Aruba
16       85008561     Aruba
17       85008561     Aruba
18       85008561     Aruba
19       85008561     Aruba
20       85008561     Aruba
21       85008561     Aruba
22       85008561     Aruba
23       85008561     Aruba
24       85008561     Aruba
25       85008561     Aruba
26       85008561     Aruba
27       85008561     Aruba
28       85008561     Aruba
29       85008561     Aruba
...           ...       ...
1352381  66003233     Samoa
1352382  66003233     Samoa
1352383  66005305     Samoa
1352384  66005305     Samoa
1352385  66005305     Samoa
1352386  66001047     Samoa
1352387  66004302     Samoa
1352388  66005378     Samoa
1352389  66005170     Samoa
1352390  66002180     Samoa
1352391  66002180     Samoa
1352392  66005107     Samoa
1352393  66004354     Samoa
1352394  66002941     Samoa
1352395  66005116     Samoa
1352396  66005019  Pakistan
1352397  66005268     Samoa
1352398  66002528     Samoa
1352399  66001893     Samoa
1352400  66003658     Samoa
1352401  66004065     Samoa
1352402  66000388     Samoa
1352403  66003276     Samoa
1352404  66004625     Samoa
1352405  66005381     India
1352406  66005381     Samoa
1352407  66005369     Samoa
1352408  66005369     Samoa
1352409  66001573     Samoa
1352410  66001573     Samoa

[1352411 rows x 2 columns]

In [15]:
countries = df.append(pd.read_sql("""
select node_id, countries from address


""", conn), ignore_index = True)
countries

          node_id           countries
0        85004929               Aruba
1        85004929               Aruba
2        85008443               Aruba
3        85008450               Aruba
4        85008462               Aruba
5        85008483               Aruba
6        85008517               Aruba
7        85008542               Aruba
8        85008549               Aruba
9        85008559               Aruba
10       85008561               Aruba
11       85008561               Aruba
12       85008561               Aruba
13       85008561               Aruba
14       85008561               Aruba
15       85008561               Aruba
16       85008561               Aruba
17       85008561               Aruba
18       85008561               Aruba
19       85008561               Aruba
20       85008561               Aruba
21       85008561               Aruba
22       85008561               Aruba
23       85008561               Aruba
24       85008561               Aruba
25       85008561               Aruba
26       85008561               Aruba
27       85008561               Aruba
28       85008561               Aruba
29       85008561               Aruba
...           ...                 ...
1575731  68001665               China
1575732  68001666         New Zealand
1575733  68001667               Samoa
1575734  68001668               Japan
1575735  68001669                Fiji
1575736  68001670               Spain
1575737  68001671               China
1575738  68001672           Hong Kong
1575739  68001673               China
1575740  68001674               Samoa
1575741  68001675               Samoa
1575742  68001676               China
1575743  68001677               Japan
1575744  68001678               China
1575745  68001679               Samoa
1575746  68001680               Samoa
1575747  68001681                Fiji
1575748  68001682  Korea, Republic of
1575749  68001683           Australia
1575750  68001684               Samoa
1575751  68001685               Samoa
1575752  68001686               Japan
1575753  68001687               Samoa
1575754  68001688            Thailand
1575755  68001689               China
1575756  68001690               Samoa
1575757  68001691               Samoa
1575758  68001692               Samoa
1575759  68001693               Samoa
1575760  68001694               Samoa

[1575761 rows x 2 columns]

In [9]:
edges.head()

,START_ID,TYPE,END_ID,link,start_date,end_date,sourceID,valid_until
0,85004927,registered_address,88000379,registered address,NaN,NaN,Paradise Papers - Aruba corporate registry,Aruba corporate registry data is current throu...
1,85004928,registered_address,88016409,registered address,NaN,NaN,Paradise Papers - Aruba corporate registry,Aruba corporate registry data is current throu...
2,85004929,registered_address,88005855,registered address,NaN,NaN,Paradise Papers - Aruba corporate registry,Aruba corporate registry data is current throu...
3,85004929,connected_to,85008101,connected to,NaN,NaN,Paradise Papers - Aruba corporate registry,Aruba corporate registry data is current throu...
4,85004929,connected_to,85021444,connected to,NaN,NaN,Paradise Papers - Aruba corporate registry,Aruba corporate registry data is current throu...

In [10]:
merged_df = edges.merge(countries, left_on="START_ID", right_on= "node_id")

In [11]:
merged_df = merged_df.merge(countries, left_on="END_ID", right_on= "node_id", suffixes = ("_start", "_end"))

In [12]:
filtered_df = merged_df[(merged_df["countries_start"] != merged_df["countries_end"]) & (merged_df["countries_start"].isnull() == False) & (merged_df["countries_end"].isnull() == False)]

In [13]:
filtered_df.to_csv("filtered_countries.csv")

In [9]:
level1 = df
level1.to_sql("level1", conn, if_exists = "replace")

In [26]:
test = edges.merge(level1, left_on="END_ID", right_on="node_id")
test = test.drop(['node_id'], axis = 1)
test = test.rename(columns = {"START_ID": 'node_id'})
test

,index,node_id,TYPE,END_ID,link,start_date,end_date,sourceID,valid_until,countries
0,19,85008443,connected_to,85011025,connected to,None,None,Paradise Papers - Aruba corporate registry,Aruba corporate registry data is current throu...,Aruba
1,27,85008450,same_name_as,86026649,same name as,None,None,Paradise Papers - Aruba corporate registry,Aruba corporate registry data is current throu...,Aruba
2,62,85008483,same_name_as,86003171,same name as,None,None,Paradise Papers - Aruba corporate registry,Aruba corporate registry data is current throu...,Aruba
3,97,85008517,connected_to,85022984,connected to,None,None,Paradise Papers - Aruba corporate registry,Aruba corporate registry data is current throu...,Aruba
4,462504,86006905,officer_of,85022984,managing director of,20-JUL-1989,None,Paradise Papers - Aruba corporate registry,Aruba corporate registry data is current throu...,Aruba
5,479516,86014531,officer_of,85022984,proxy of,12-MAR-1998,None,Paradise Papers - Aruba corporate registry,Aruba corporate registry data is current throu...,Aruba
6,487146,86017477,officer_of,85022984,managing director of,01-JUN-1996,None,Paradise Papers - Aruba corporate registry,Aruba corporate registry data is current throu...,Aruba
7,122,85008542,connected_to,85010050,connected to,None,None,Paradise Papers - Aruba corporate registry,Aruba corporate registry data is current throu...,Aruba
8,130,85008549,same_name_as,85004666,same name as,None,None,Paradise Papers - Aruba corporate registry,Aruba corporate registry data is current throu...,Aruba
9,500611,86023066,officer_of,85004666,managing director of,18-JAN-2002,None,Paradise Papers - Aruba corporate registry,Aruba corporate registry data is current throu...,Aruba
10,141,85008559,same_name_as,85007594,same name as,None,None,Paradise Papers - Aruba corporate registry,Aruba corporate registry data is current throu...,Aruba
11,487175,86017496,officer_of,85007594,managing director of,03-NOV-1988,None,Paradise Papers - Aruba corporate registry,Aruba corporate registry data is current throu...,Aruba
12,144,85008561,same_name_as,86021159,same name as,None,None,Paradise Papers - Aruba corporate registry,Aruba corporate registry data is current throu...,Aruba
13,144,85008561,same_name_as,86021159,same name as,None,None,Paradise Papers - Aruba corporate registry,Aruba corporate registry data is current throu...,Aruba
14,144,85008561,same_name_as,86021159,same name as,None,None,Paradise Papers - Aruba corporate registry,Aruba corporate registry data is current throu...,Aruba
15,144,85008561,same_name_as,86021159,same name as,None,None,Paradise Papers - Aruba corporate registry,Aruba corporate registry data is current throu...,Aruba
16,144,85008561,same_name_as,86021159,same name as,None,None,Paradise Papers - Aruba corporate registry,Aruba corporate registry data is current throu...,Aruba
17,144,85008561,same_name_as,86021159,same name as,None,None,Paradise Papers - Aruba corporate registry,Aruba corporate registry data is current throu...,Aruba
18,144,85008561,same_name_as,86021159,same name as,None,None,Paradise Papers - Aruba corporate registry,Aruba corporate registry data is current throu...,Aruba
19,144,85008561,same_name_as,86021159,same name as,None,None,Paradise Papers - Aruba corporate registry,Aruba corporate registry data is current throu...,Aruba
20,144,85008561,same_name_as,86021159,same name as,None,None,Paradise Papers - Aruba corporate registry,Aruba corporate registry data is current throu...,Aruba
21,144,85008561,same_name_as,86021159,same name as,None,None,Paradise Papers - Aruba corporate registry,Aruba corporate registry data is current throu...,Aruba
22,144,85008561,same_name_as,86021159,same name as,None,None,Paradise Papers - Aruba corporate registry,Aruba corporate registry data is current throu...,Aruba
23,144,85008561,same_name_as,86021159,same name as,None,None,Paradise Papers - Aruba corporate registry,Aruba corporate registry data is current throu...,Aruba
24,144,85008561,same_name_as,86021159,same name as,None,None,Paradise Papers - Aruba corporate registry,Aruba corporate registry data is current throu...,Aruba
25,144,85008561,same_name_as,86021159,same name as,None,None,Paradise Papers - Aruba corporate registry,Aruba corporate registry data is current throu...,Aruba
26,144,85008561,same_name_as,86021159,same name as,None,None,Paradise Papers - Aruba corporate registry,Aruba corporate registry data is current throu...,Aruba
27,144,85008561,same_name_as,86021159,same name as,None,None,Paradise Papers - Aruba corporate registry,Aruba corporate registry data is current throu...,Aruba
28,144,85008561,same_name_as,86021159,same name as,None,None,Paradise Papers - Aruba corporate registry,Aruba corporate registry data is current throu...,Aruba
29,144,85008561,same_name_as,86021159,same name as,None,None,Paradise Papers - Aruba corporate registry,Aruba corporate registry data is current throu...,Aruba
...,...,...,...,...,...,...,...,...,...,...
149967,1656795,66002924,officer_of,65000332,former director of,15-Sep-1985,30-Sep-2014,Paradise Papers - Samoa corporate registry,Samoa corporate registry data is current throu...,Samoa
149968,1657473,66002925,officer_of,65000332,former shareholder of,15-Sep-1985,30-Sep-2014,Paradise Papers - Samoa corporate registry,Samoa corporate registry data is current throu...,Samoa
149969,1646133,66000520,officer_of,65000304,director of,10-Sep-2009,None,Paradise Papers - Samoa corporate registry,Samoa corporate registry data is current throu...,Samoa
149970,1646135,66000520,officer_of,65000304,shareholder of,10-Sep-2009,None,Paradise Papers - Samoa corporate registry,Samoa corporate registry data is current throu...,Samoa
149971,1651930,66000517,officer_of,65000304,shareholder of,10-Sep-2009,None,Paradise Papers - Samoa corporate registry,Samoa corporate registry data is current throu...,Samoa
149972,1651940,66000517,officer_of,65000304,director of,10-Sep-2009,None,Paradise Papers - Samoa corporate registry,Samoa corporate registry data is current throu...,Samoa
149973,1646139,66003027,officer_of,65000837,director of,16-Sep-2010,None,Paradise Papers - Samoa corporate registry,Samoa corporate registry data is current throu...,Samoa
149974,1646140,66003027,officer_of,65000837,shareholder of,16-Sep-2010,None,Paradise Papers - Samoa corporate registry,Samoa corporate registry data is current throu...,Samoa
149975,1650710,66002909,officer_of,65000837,director of,16-Sep-2010,None,Paradise Papers - Samoa corporate registry,Samoa corporate registry data is current throu...,Samoa
149976,1650711,66002909,officer_of,65000837,shareholder of,16-Sep-2010,None,Paradise Papers - Samoa corporate registry,Samoa corporate registry data is current throu...,Samoa
149977,1652190,66002847,officer_of,65000837,director of,16-Sep-2010,None,Paradise Papers - Samoa corporate registry,Samoa corporate registry data is current throu...,Samoa
149978,1652192,66002847,officer_of,65000837,shareholder of,16-Sep-2010,None,Paradise Papers - Samoa corporate registry,Samoa corporate registry data is current throu...,Samoa
149979,1646185,66002754,officer_of,65000270,shareholder of,27-Oct-2005,None,Paradise Papers - Samoa corporate registry,Samoa corporate registry data is current throu...,Samoa
149980,1647798,66002768,officer_of,65000270,shareholder of,27-Oct-2005,None,Paradise Papers - Samoa corporate registry,Samoa corporate registry data is current throu...,Samoa
149981,1647799,66002768,officer_of,65000270,director of,27-Oct-2005,None,Paradise Papers - Samoa corporate registry,Samoa corporate registry data is current throu...,Samoa
149982,1654333,66002759,officer_of,65000270,director of,27-Oct-2005,None,Paradise Papers - Samoa corporate registry,Samoa corporate registry data is current throu...,Samoa
149983,1654334,66002759,officer_of,65000270,shareholder of,27-Oct-2005,None,Paradise Papers - Samoa corporate registry,Samoa corporate registry data is current throu...,Samoa
149984,1647642,66001348,officer_of,65000095,director of,26-Mar-1992,None,Paradise Papers - Samoa corporate registry,Samoa corporate registry data is current throu...,Samoa
149985,1647643,66001348,officer_of,65000095,shareholder of,26-Mar-1992,None,Paradise Papers - Samoa corporate registry,Samoa corporate registry data is current throu...,Samoa
149986,1648913,66001314,officer_of,65000095,shareholder of,26-Mar-1992,None,Paradise Papers - Samoa corporate registry,Samoa corporate registry data is current throu...,Samoa
149987,1649307,66001382,officer_of,65000095,shareholder of,26-Mar-1992,None,Paradise Papers - Samoa corporate registry,Samoa corporate registry data is current throu...,Samoa
149988,1649309,66001382,officer_of,65000095,director of,26-Mar-1992,None,Paradise Papers - Samoa corporate registry,Samoa corporate registry data is current throu...,Samoa
149989,1650065,66005208,officer_of,65000095,director of,05-Jul-2013,None,Paradise Papers - Samoa corporate registry,Samoa corporate registry data is current throu...,Samoa
149990,1653884,66001365,officer_of,65000095,shareholder of,26-Mar-1992,None,Paradise Papers - Samoa corporate registry,Samoa corporate registry data is current throu...,Samoa
149991,1655184,66001381,officer_of,65000095,shareholder of,26-Mar-1992,None,Paradise Papers - Samoa corporate registry,Samoa corporate registry data is current throu...,Samoa
149992,1655804,66001369,officer_of,65000095,shareholder of,26-Mar-1992,None,Paradise Papers - Samoa corporate registry,Samoa corporate registry data is current throu...,Samoa
149993,1650908,66002827,officer_of,65000645,director of,03-Jul-1998,None,Paradise Papers - Samoa corporate registry,Samoa corporate registry data is current throu...,Samoa
149994,1650909,66002827,officer_of,65000645,shareholder of,03-Jul-1998,None,Paradise Papers - Samoa corporate registry,Samoa corporate registry data is current throu...,Samoa
149995,1657537,66001951,officer_of,65000645,director of,03-Jul-1998,None,Paradise Papers - Samoa corporate registry,Samoa corporate registry data is current throu...,Samoa
149996,1657538,66001951,officer_of,65000645,shareholder of,03-Jul-1998,None,Paradise Papers - Samoa corporate registry,Samoa corporate registry data is current throu...,Samoa

In [29]:
more_countries = countries.append(test.loc[:, lambda df: ['node_id', 'countries']], ignore_index = True)

<bound method DataFrame.count of           node_id countries
0        85004929     Aruba
1        85004929     Aruba
2        85008443     Aruba
3        85008450     Aruba
4        85008462     Aruba
5        85008483     Aruba
6        85008517     Aruba
7        85008542     Aruba
8        85008549     Aruba
9        85008559     Aruba
10       85008561     Aruba
11       85008561     Aruba
12       85008561     Aruba
13       85008561     Aruba
14       85008561     Aruba
15       85008561     Aruba
16       85008561     Aruba
17       85008561     Aruba
18       85008561     Aruba
19       85008561     Aruba
20       85008561     Aruba
21       85008561     Aruba
22       85008561     Aruba
23       85008561     Aruba
24       85008561     Aruba
25       85008561     Aruba
26       85008561     Aruba
27       85008561     Aruba
28       85008561     Aruba
29       85008561     Aruba
...           ...       ...
1725728  66002924     Samoa
1725729  66002925     Samoa
1725730  66000520     Samoa
1725731  66000520     Samoa
1725732  66000517     Samoa
1725733  66000517     Samoa
1725734  66003027     Samoa
1725735  66003027     Samoa
1725736  66002909     Samoa
1725737  66002909     Samoa
1725738  66002847     Samoa
1725739  66002847     Samoa
1725740  66002754     Samoa
1725741  66002768     Samoa
1725742  66002768     Samoa
1725743  66002759     Samoa
1725744  66002759     Samoa
1725745  66001348     Samoa
1725746  66001348     Samoa
1725747  66001314     Samoa
1725748  66001382     Samoa
1725749  66001382     Samoa
1725750  66005208     Samoa
1725751  66001365     Samoa
1725752  66001381     Samoa
1725753  66001369     Samoa
1725754  66002827     Samoa
1725755  66002827     Samoa
1725756  66001951     Samoa
1725757  66001951     Samoa

[1725758 rows x 2 columns]>

In [30]:
bigger_merged_df = edges.merge(more_countries, left_on="START_ID", right_on= "node_id")
bigger_merged_df = bigger_merged_df.merge(more_countries, left_on="END_ID", right_on= "node_id", suffixes = ("_start", "_end"))

In [32]:
bigger_filtered_df = bigger_merged_df[(bigger_merged_df["countries_start"].isnull() == False) & (bigger_merged_df["countries_end"].isnull() == False)]

,index,START_ID,TYPE,END_ID,link,start_date,end_date,sourceID,valid_until,node_id_start,countries_start,node_id_end,countries_end
0,2,85004929,registered_address,88005855,registered address,None,None,Paradise Papers - Aruba corporate registry,Aruba corporate registry data is current throu...,85004929,Aruba,88005855,Aruba
2,421146,85028458,registered_address,88005855,registered address,None,None,Paradise Papers - Aruba corporate registry,Aruba corporate registry data is current throu...,85028458,Aruba,88005855,Aruba
4,18,85008443,registered_address,88007215,registered address,None,None,Paradise Papers - Aruba corporate registry,Aruba corporate registry data is current throu...,85008443,Aruba,88007215,Aruba
6,217,85008634,registered_address,88007215,registered address,None,None,Paradise Papers - Aruba corporate registry,Aruba corporate registry data is current throu...,85008634,Aruba,88007215,Aruba
8,634,85009035,registered_address,88007215,registered address,None,None,Paradise Papers - Aruba corporate registry,Aruba corporate registry data is current throu...,85009035,Aruba,88007215,Aruba
10,1623,85009973,registered_address,88007215,registered address,None,None,Paradise Papers - Aruba corporate registry,Aruba corporate registry data is current throu...,85009973,Aruba,88007215,Aruba
11,383326,85010654,registered_address,88007215,registered address,None,None,Paradise Papers - Aruba corporate registry,Aruba corporate registry data is current throu...,85010654,Aruba,88007215,Aruba
12,383827,85011128,registered_address,88007215,registered address,None,None,Paradise Papers - Aruba corporate registry,Aruba corporate registry data is current throu...,85011128,Aruba,88007215,Aruba
14,387517,85002580,registered_address,88007215,registered address,None,None,Paradise Papers - Aruba corporate registry,Aruba corporate registry data is current throu...,85002580,Aruba,88007215,Aruba
15,387734,85002793,registered_address,88007215,registered address,None,None,Paradise Papers - Aruba corporate registry,Aruba corporate registry data is current throu...,85002793,Aruba,88007215,Aruba
21,388888,85005111,registered_address,88007215,registered address,None,None,Paradise Papers - Aruba corporate registry,Aruba corporate registry data is current throu...,85005111,Aruba,88007215,Aruba
23,389427,85005700,registered_address,88007215,registered address,None,None,Paradise Papers - Aruba corporate registry,Aruba corporate registry data is current throu...,85005700,Aruba,88007215,Aruba
25,389501,85005774,registered_address,88007215,registered address,None,None,Paradise Papers - Aruba corporate registry,Aruba corporate registry data is current throu...,85005774,Aruba,88007215,Aruba
45,389581,85005840,registered_address,88007215,registered address,None,None,Paradise Papers - Aruba corporate registry,Aruba corporate registry data is current throu...,85005840,Aruba,88007215,Aruba
47,389649,85005902,registered_address,88007215,registered address,None,None,Paradise Papers - Aruba corporate registry,Aruba corporate registry data is current throu...,85005902,Aruba,88007215,Aruba
49,390075,85006314,registered_address,88007215,registered address,None,None,Paradise Papers - Aruba corporate registry,Aruba corporate registry data is current throu...,85006314,Aruba,88007215,Aruba
51,390142,85006362,registered_address,88007215,registered address,None,None,Paradise Papers - Aruba corporate registry,Aruba corporate registry data is current throu...,85006362,Aruba,88007215,Aruba
54,391057,85007223,registered_address,88007215,registered address,None,None,Paradise Papers - Aruba corporate registry,Aruba corporate registry data is current throu...,85007223,Aruba,88007215,Aruba
59,391878,85007994,registered_address,88007215,registered address,None,None,Paradise Papers - Aruba corporate registry,Aruba corporate registry data is current throu...,85007994,Aruba,88007215,Aruba
63,392129,85008228,registered_address,88007215,registered address,None,None,Paradise Papers - Aruba corporate registry,Aruba corporate registry data is current throu...,85008228,Aruba,88007215,Aruba
64,403743,85012041,registered_address,88007215,registered address,None,None,Paradise Papers - Aruba corporate registry,Aruba corporate registry data is current throu...,85012041,Aruba,88007215,Aruba
66,409722,85017788,registered_address,88007215,registered address,None,None,Paradise Papers - Aruba corporate registry,Aruba corporate registry data is current throu...,85017788,Aruba,88007215,Aruba
69,410265,85018315,registered_address,88007215,registered address,None,None,Paradise Papers - Aruba corporate registry,Aruba corporate registry data is current throu...,85018315,Aruba,88007215,Aruba
70,411068,85019079,registered_address,88007215,registered address,None,None,Paradise Papers - Aruba corporate registry,Aruba corporate registry data is current throu...,85019079,Aruba,88007215,Aruba
72,411184,85019182,registered_address,88007215,registered address,None,None,Paradise Papers - Aruba corporate registry,Aruba corporate registry data is current throu...,85019182,Aruba,88007215,Aruba
75,411989,85019939,registered_address,88007215,registered address,None,None,Paradise Papers - Aruba corporate registry,Aruba corporate registry data is current throu...,85019939,Aruba,88007215,Aruba
76,413237,85021100,registered_address,88007215,registered address,None,None,Paradise Papers - Aruba corporate registry,Aruba corporate registry data is current throu...,85021100,Aruba,88007215,Aruba
81,413260,85021117,registered_address,88007215,registered address,None,None,Paradise Papers - Aruba corporate registry,Aruba corporate registry data is current throu...,85021117,Aruba,88007215,Aruba
83,414702,85022482,registered_address,88007215,registered address,None,None,Paradise Papers - Aruba corporate registry,Aruba corporate registry data is current throu...,85022482,Aruba,88007215,Aruba
86,415630,85023338,registered_address,88007215,registered address,None,None,Paradise Papers - Aruba corporate registry,Aruba corporate registry data is current throu...,85023338,Aruba,88007215,Aruba
...,...,...,...,...,...,...,...,...,...,...,...,...,...
41056900,1657233,66005165,registered_address,68001321,registered address,None,None,Paradise Papers - Samoa corporate registry,Samoa corporate registry data is current throu...,66005165,Panama,68001321,Panama
41056901,1657238,66003816,registered_address,68000510,registered address,None,None,Paradise Papers - Samoa corporate registry,Samoa corporate registry data is current throu...,66003816,Samoa,68000510,Samoa
41056902,1657263,66005156,registered_address,68001312,registered address,None,None,Paradise Papers - Samoa corporate registry,Samoa corporate registry data is current throu...,66005156,Samoa,68001312,Samoa
41056905,1657343,66005004,registered_address,68001184,registered address,None,None,Paradise Papers - Samoa corporate registry,Samoa corporate registry data is current throu...,66005004,Samoa,68001184,Samoa
41056906,1657352,66004766,registered_address,68001011,registered address,None,None,Paradise Papers - Samoa corporate registry,Samoa corporate registry data is current throu...,66004766,Samoa,68001011,Samoa
41056907,1657368,66004823,registered_address,68001051,registered address,None,None,Paradise Papers - Samoa corporate registry,Samoa corporate registry data is current throu...,66004823,Samoa,68001051,Samoa
41056908,1657384,66004180,registered_address,68000655,registered address,None,None,Paradise Papers - Samoa corporate registry,Samoa corporate registry data is current throu...,66004180,Samoa,68000655,Samoa
41056910,1657388,66005100,registered_address,68001266,registered address,None,None,Paradise Papers - Samoa corporate registry,Samoa corporate registry data is current throu...,66005100,Samoa,68001266,Samoa
41056911,1657411,66002501,registered_address,68000223,registered address,None,None,Paradise Papers - Samoa corporate registry,Samoa corporate registry data is current throu...,66002501,Samoa,68000223,New Zealand
41056912,1657440,66004894,registered_address,68001095,registered address,None,None,Paradise Papers - Samoa corporate registry,Samoa corporate registry data is current throu...,66004894,India,68001095,India
41056913,1657460,66003459,registered_address,68000400,registered address,None,None,Paradise Papers - Samoa corporate registry,Samoa corporate registry data is current throu...,66003459,Samoa,68000400,Samoa
41056914,1657492,66004995,registered_address,68001176,registered address,None,None,Paradise Papers - Samoa corporate registry,Samoa corporate registry data is current throu...,66004995,Samoa,68001176,Samoa
41056917,1657495,66004995,same_name_as,66004143,same name as,None,None,Paradise Papers - Samoa corporate registry,Samoa corporate registry data is current throu...,66004995,Samoa,66004143,Samoa
41056920,1657519,66002596,registered_address,68000231,registered address,None,None,Paradise Papers - Samoa corporate registry,Samoa corporate registry data is current throu...,66002596,Samoa,68000231,Samoa
41056922,1657526,66004252,registered_address,68000696,registered address,None,None,Paradise Papers - Samoa corporate registry,Samoa corporate registry data is current throu...,66004252,Samoa,68000696,Samoa
41056924,1657530,66005608,same_name_as,66003138,same name as,None,None,Paradise Papers - Samoa corporate registry,Samoa corporate registry data is current throu...,66005608,New Zealand,66003138,Samoa
41056925,1657530,66005608,same_name_as,66003138,same name as,None,None,Paradise Papers - Samoa corporate registry,Samoa corporate registry data is current throu...,66005608,Samoa,66003138,Samoa
41056926,1657551,66003427,registered_address,68000385,registered address,None,None,Paradise Papers - Samoa corporate registry,Samoa corporate registry data is current throu...,66003427,Samoa,68000385,Samoa
41056928,1657563,66005305,registered_address,68001442,registered address,None,None,Paradise Papers - Samoa corporate registry,Samoa corporate registry data is current throu...,66005305,Samoa,68001442,Samoa
41056931,1657607,66005378,registered_address,68001503,registered address,None,None,Paradise Papers - Samoa corporate registry,Samoa corporate registry data is current throu...,66005378,Samoa,68001503,Samoa
41056932,1657611,66005170,registered_address,68001325,registered address,None,None,Paradise Papers - Samoa corporate registry,Samoa corporate registry data is current throu...,66005170,Samoa,68001325,New Zealand
41056933,1657635,66005107,registered_address,68001273,registered address,None,None,Paradise Papers - Samoa corporate registry,Samoa corporate registry data is current throu...,66005107,Samoa,68001273,Samoa
41056934,1657641,66004354,registered_address,68000754,registered address,None,None,Paradise Papers - Samoa corporate registry,Samoa corporate registry data is current throu...,66004354,Samoa,68000754,Samoa
41056935,1657670,66005116,registered_address,68001279,registered address,None,None,Paradise Papers - Samoa corporate registry,Samoa corporate registry data is current throu...,66005116,Samoa,68001279,Samoa
41056936,1657671,66005116,same_name_as,66000582,same name as,None,None,Paradise Papers - Samoa corporate registry,Samoa corporate registry data is current throu...,66005116,Samoa,66000582,Samoa
41056938,1657680,66005268,registered_address,68001408,registered address,None,None,Paradise Papers - Samoa corporate registry,Samoa corporate registry data is current throu...,66005268,Samoa,68001408,Samoa
41056939,1657703,66003658,registered_address,68000452,registered address,None,None,Paradise Papers - Samoa corporate registry,Samoa corporate registry data is current throu...,66003658,Samoa,68000452,Samoa
41056940,1657750,66005381,registered_address,68001505,registered address,None,None,Paradise Papers - Samoa corporate registry,Samoa corporate registry data is current throu...,66005381,India,68001505,India
41056941,1657750,66005381,registered_address,68001505,registered address,None,None,Paradise Papers - Samoa corporate registry,Samoa corporate registry data is current throu...,66005381,Samoa,68001505,India
41056942,1657756,66005369,registered_address,68001495,registered address,None,None,Paradise Papers - Samoa corporate registry,Samoa corporate registry data is current throu...,66005369,Samoa,68001495,Samoa

In [37]:
bigger_filtered_df = bigger_filtered_df.drop_duplicates()

In [46]:
# bigger_filtered_df.loc[:, lambda df: ['START_ID', 'END_ID', 'countries_start', 'countries_end']]
temp = bigger_filtered_df.loc[:, lambda df: ['countries_start', 'countries_end']]
temp.drop_duplicates()

                  countries_start            countries_end
0                           Aruba                    Aruba
789846              United States                    Aruba
790834             Cayman Islands                  Bermuda
790835                      China                  Bermuda
790836                    Bermuda                  Bermuda
790837                  Hong Kong                  Bermuda
790845                  Singapore                  Bermuda
790847              United States                  Bermuda
790937                     Taiwan                  Bermuda
790990                Philippines                  Bermuda
791079             United Kingdom                  Bermuda
791146                Switzerland                  Bermuda
791190                     Canada                  Bermuda
791193     British Virgin Islands                  Bermuda
791198                   Pakistan                  Bermuda
791200                      India                  Bermuda
791346                   Guernsey                  Bermuda
791398                     Russia                  Bermuda
791408                    Ireland                  Bermuda
791443                    Bahamas                  Bermuda
791571                     Jersey                  Bermuda
791695                    Austria                  Bermuda
791881                  Australia                  Bermuda
792519                    Germany                  Bermuda
792555                Isle of Man                  Bermuda
792620                  Mauritius                  Bermuda
792634                     Mexico                  Bermuda
792648                   Malaysia                  Bermuda
792981                    Ukraine                  Bermuda
793039                     Norway                  Bermuda
...                           ...                      ...
32924663      Antigua and Barbuda    Saint Kitts and Nevis
32924686           Not identified    Saint Kitts and Nevis
32924690                  Austria    Saint Kitts and Nevis
32924696                   Russia    Saint Kitts and Nevis
32924711               Azerbaijan    Saint Kitts and Nevis
41055847              New Zealand                    Samoa
41056009               Tajikistan                    Samoa
41056016          Solomon Islands                    Samoa
41056057                     Fiji                     Fiji
41056068                    Samoa                     Fiji
41056091                 Pakistan                    Samoa
41056099             Cook Islands                Australia
41056180  Virgin Islands, British  Virgin Islands, British
41056246                    Samoa                Australia
41056259                Australia                    Samoa
41056270                    Samoa              New Zealand
41056336                    Tonga                    Tonga
41056358                    Samoa                Hong Kong
41056436           American Samoa           American Samoa
41056468             Cook Islands             Cook Islands
41056486                    Samoa                    Tonga
41056546                    Samoa                  Vanuatu
41056573                    Samoa           American Samoa
41056644               San Marino                    Samoa
41056662                    Samoa                    China
41056758           American Samoa                    Samoa
41056769                    Samoa                    Japan
41056828         Papua New Guinea         Papua New Guinea
41056857                  Vanuatu                    Samoa
41056941                    Samoa                    India

[2852 rows x 2 columns]

In [ ]:
dataframe['countries'].replace('Curaçao', 'Curacao')
dataframe['countries'].replace("Côte d'Ivoire", "Cote d'Ivoire")
dataframe['countries'].replace('Virgin Islands, British', 'British Virgin Islands')
dataframe['countries'].replace('Bolivarian Republic of Venezuela', 'Venezuela')
dataframe['countries'].replace('U.S. Virgin Islands', 'Virgin Islands, U.S.')