In [1]:
import pandas as pd
import numpy as np

In [2]:

data = pd.read_csv("filtered_countries.csv")

/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [14]:
data_edges = data[["countries_start", "countries_end"]]
data_edges = data_edges.rename(columns = {"countries_start" : "Source", "countries_end": "Target"})
data_edges.drop_duplicates()

                        Source                 Target
0                United States                  Aruba
1               Cayman Islands                Bermuda
2                        China                Bermuda
3                    Hong Kong                Bermuda
7                    Singapore                Bermuda
8                United States                Bermuda
44                      Taiwan                Bermuda
65                 Philippines                Bermuda
111             United Kingdom                Bermuda
141                Switzerland                Bermuda
152                     Canada                Bermuda
153     British Virgin Islands                Bermuda
154                   Pakistan                Bermuda
155                      India                Bermuda
170                   Guernsey                Bermuda
183                     Russia                Bermuda
185                    Ireland                Bermuda
191                    Bahamas                Bermuda
204                     Jersey                Bermuda
224                    Austria                Bermuda
251                  Australia                Bermuda
267                    Germany                Bermuda
268                Isle of Man                Bermuda
270                  Mauritius                Bermuda
272                     Mexico                Bermuda
273                   Malaysia                Bermuda
297                    Ukraine                Bermuda
303                     Norway                Bermuda
304                     Cyprus                Bermuda
312                     Monaco                Bermuda
...                        ...                    ...
480814                   Spain  Saint Kitts and Nevis
480815                 Grenada  Saint Kitts and Nevis
480820                Colombia  Saint Kitts and Nevis
480821               Australia  Saint Kitts and Nevis
480823               Guatemala  Saint Kitts and Nevis
480824    United Arab Emirates  Saint Kitts and Nevis
480825                   China  Saint Kitts and Nevis
480832     Antigua and Barbuda  Saint Kitts and Nevis
480834          Not identified  Saint Kitts and Nevis
480837                 Austria  Saint Kitts and Nevis
480842                  Russia  Saint Kitts and Nevis
480852              Azerbaijan  Saint Kitts and Nevis
480856              Tajikistan                  Samoa
480857         Solomon Islands                  Samoa
480858                   Samoa                   Fiji
480859                Pakistan                  Samoa
480861            Cook Islands              Australia
480862             New Zealand                  Samoa
480863                   Samoa              Australia
480865               Australia                  Samoa
480866                   Samoa            New Zealand
480882                   Samoa                  Tonga
480888                   Samoa                Vanuatu
480889                   Samoa         American Samoa
480897              San Marino                  Samoa
480899                   Samoa                  China
480903          American Samoa                  Samoa
480908                   Samoa                  Japan
480920                 Vanuatu                  Samoa
480929                   Samoa                  India

[2111 rows x 2 columns]

In [13]:
data_nodes = data[["countries_start"]]
data_nodes_2 = data[["countries_end"]]

data_nodes = data_nodes.rename(columns= {"node_id_start": "Id", "countries_start": "Label"})

data_nodes_2 = data_nodes_2.rename(columns= {"node_id_end": "Id", "countries_end": "Label"})

In [5]:
data_nodes = data_nodes.append(data_nodes_2)

In [6]:
data_nodes = data_nodes.drop_duplicates()

In [7]:

data_edges.to_csv("data_edges.csv", index= False)

In [8]:
data_nodes.to_csv("data_nodes.csv", index = False)